// SurveyField contains logic to render a single label and text input
import React from "react";

// pulls off the input, the label and the meta properties from the props object
/*
 * The input prop have the following properties:
 *  - name
 *  - value
 *  - onBlur
 *  - onChange
 *  - onDragStart
 *  - onDrop
 *  - onFocus
 * The meta prop contains the errors generated by the validation function. Besides the errors,
 * it also contains a prop call "touched" which indicate if the user clicked in the field of the form.
 * meta : { error, touched} means that we extract only those two properties from the object meta
 */
export default ({ input, label, meta: { error, touched } }) => {
  /*
   * Spread notation: {...input} equals to name={input.name} onBlur={input.onBlur} onChange={input.onChange} etc,
   * in other words, that's the equivalent of having to write down by hand all the props from the input object.
   */
  /*
   * { touched && error }: touched is a boolean and error a String. If touched is true and error exists, then
   * show the error String. If touched is false, then nothing will show up.
   */
  return (
    <div>
      <label>{label}</label>
      <input {...input} style={{ marginBottom: "5px" }} />
      <div className="red-text" style={{ marginBottom: "20px" }}>
        {touched && error}
      </div>
    </div>
  );
};
